// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/agent/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type SocialPlatform int32

const (
	SocialPlatform_TWITTER   SocialPlatform = 0
	SocialPlatform_INSTAGRAM SocialPlatform = 1
	SocialPlatform_FACEBOOK  SocialPlatform = 2
	SocialPlatform_LINKEDIN  SocialPlatform = 3
)

// Enum value maps for SocialPlatform.
var (
	SocialPlatform_name = map[int32]string{
		0: "TWITTER",
		1: "INSTAGRAM",
		2: "FACEBOOK",
		3: "LINKEDIN",
	}
	SocialPlatform_value = map[string]int32{
		"TWITTER":   0,
		"INSTAGRAM": 1,
		"FACEBOOK":  2,
		"LINKEDIN":  3,
	}
)

func (x SocialPlatform) Enum() *SocialPlatform {
	p := new(SocialPlatform)
	*p = x
	return p
}

func (x SocialPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SocialPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[0].Descriptor()
}

func (SocialPlatform) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[0]
}

func (x SocialPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SocialPlatform.Descriptor instead.
func (SocialPlatform) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

type ToneType int32

const (
	ToneType_PROFESSIONAL  ToneType = 0
	ToneType_CASUAL        ToneType = 1
	ToneType_FRIENDLY      ToneType = 2
	ToneType_AUTHORITATIVE ToneType = 3
	ToneType_HUMOROUS      ToneType = 4
	ToneType_INSPIRATIONAL ToneType = 5
	ToneType_WITTY         ToneType = 6
	ToneType_FUNNY         ToneType = 7
	ToneType_SARCASTIC     ToneType = 8
	ToneType_ENTHUSIASTIC  ToneType = 9
	ToneType_EMPATHETIC    ToneType = 10
	ToneType_CONFIDENT     ToneType = 11
)

// Enum value maps for ToneType.
var (
	ToneType_name = map[int32]string{
		0:  "PROFESSIONAL",
		1:  "CASUAL",
		2:  "FRIENDLY",
		3:  "AUTHORITATIVE",
		4:  "HUMOROUS",
		5:  "INSPIRATIONAL",
		6:  "WITTY",
		7:  "FUNNY",
		8:  "SARCASTIC",
		9:  "ENTHUSIASTIC",
		10: "EMPATHETIC",
		11: "CONFIDENT",
	}
	ToneType_value = map[string]int32{
		"PROFESSIONAL":  0,
		"CASUAL":        1,
		"FRIENDLY":      2,
		"AUTHORITATIVE": 3,
		"HUMOROUS":      4,
		"INSPIRATIONAL": 5,
		"WITTY":         6,
		"FUNNY":         7,
		"SARCASTIC":     8,
		"ENTHUSIASTIC":  9,
		"EMPATHETIC":    10,
		"CONFIDENT":     11,
	}
)

func (x ToneType) Enum() *ToneType {
	p := new(ToneType)
	*p = x
	return p
}

func (x ToneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToneType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[1].Descriptor()
}

func (ToneType) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[1]
}

func (x ToneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToneType.Descriptor instead.
func (ToneType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

type StyleType int32

const (
	StyleType_FORMAL         StyleType = 0
	StyleType_CONVERSATIONAL StyleType = 1
	StyleType_STORYTELLING   StyleType = 2
	StyleType_EDUCATIONAL    StyleType = 3
	StyleType_PROMOTIONAL    StyleType = 4
	StyleType_NEWS           StyleType = 5
)

// Enum value maps for StyleType.
var (
	StyleType_name = map[int32]string{
		0: "FORMAL",
		1: "CONVERSATIONAL",
		2: "STORYTELLING",
		3: "EDUCATIONAL",
		4: "PROMOTIONAL",
		5: "NEWS",
	}
	StyleType_value = map[string]int32{
		"FORMAL":         0,
		"CONVERSATIONAL": 1,
		"STORYTELLING":   2,
		"EDUCATIONAL":    3,
		"PROMOTIONAL":    4,
		"NEWS":           5,
	}
)

func (x StyleType) Enum() *StyleType {
	p := new(StyleType)
	*p = x
	return p
}

func (x StyleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StyleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[2].Descriptor()
}

func (StyleType) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[2]
}

func (x StyleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StyleType.Descriptor instead.
func (StyleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

type MessageRole int32

const (
	MessageRole_USER      MessageRole = 0
	MessageRole_ASSISTANT MessageRole = 1
	MessageRole_SYSTEM    MessageRole = 2
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "USER",
		1: "ASSISTANT",
		2: "SYSTEM",
	}
	MessageRole_value = map[string]int32{
		"USER":      0,
		"ASSISTANT": 1,
		"SYSTEM":    2,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[3].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[3]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

type PostGenerationEvent_EventType int32

const (
	PostGenerationEvent_GENERATION_STARTED   PostGenerationEvent_EventType = 0
	PostGenerationEvent_GENERATION_PROGRESS  PostGenerationEvent_EventType = 1
	PostGenerationEvent_GENERATION_COMPLETED PostGenerationEvent_EventType = 2
	PostGenerationEvent_GENERATION_ERROR     PostGenerationEvent_EventType = 3
)

// Enum value maps for PostGenerationEvent_EventType.
var (
	PostGenerationEvent_EventType_name = map[int32]string{
		0: "GENERATION_STARTED",
		1: "GENERATION_PROGRESS",
		2: "GENERATION_COMPLETED",
		3: "GENERATION_ERROR",
	}
	PostGenerationEvent_EventType_value = map[string]int32{
		"GENERATION_STARTED":   0,
		"GENERATION_PROGRESS":  1,
		"GENERATION_COMPLETED": 2,
		"GENERATION_ERROR":     3,
	}
)

func (x PostGenerationEvent_EventType) Enum() *PostGenerationEvent_EventType {
	p := new(PostGenerationEvent_EventType)
	*p = x
	return p
}

func (x PostGenerationEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostGenerationEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[4].Descriptor()
}

func (PostGenerationEvent_EventType) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[4]
}

func (x PostGenerationEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostGenerationEvent_EventType.Descriptor instead.
func (PostGenerationEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{4, 0}
}

// Agent Service Messages
type GeneratePostRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId     *string                `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
	Platform           string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	CompanyId          *string                `protobuf:"bytes,4,opt,name=company_id,json=companyId,proto3,oneof" json:"company_id,omitempty"`
	CompanyUrl         *string                `protobuf:"bytes,5,opt,name=company_url,json=companyUrl,proto3,oneof" json:"company_url,omitempty"`
	CustomPrompt       *string                `protobuf:"bytes,6,opt,name=custom_prompt,json=customPrompt,proto3,oneof" json:"custom_prompt,omitempty"`
	IncludeCompanyData *bool                  `protobuf:"varint,7,opt,name=include_company_data,json=includeCompanyData,proto3,oneof" json:"include_company_data,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GeneratePostRequest) Reset() {
	*x = GeneratePostRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePostRequest) ProtoMessage() {}

func (x *GeneratePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePostRequest.ProtoReflect.Descriptor instead.
func (*GeneratePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GeneratePostRequest) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *GeneratePostRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GeneratePostRequest) GetCompanyId() string {
	if x != nil && x.CompanyId != nil {
		return *x.CompanyId
	}
	return ""
}

func (x *GeneratePostRequest) GetCompanyUrl() string {
	if x != nil && x.CompanyUrl != nil {
		return *x.CompanyUrl
	}
	return ""
}

func (x *GeneratePostRequest) GetCustomPrompt() string {
	if x != nil && x.CustomPrompt != nil {
		return *x.CustomPrompt
	}
	return ""
}

func (x *GeneratePostRequest) GetIncludeCompanyData() bool {
	if x != nil && x.IncludeCompanyData != nil {
		return *x.IncludeCompanyData
	}
	return false
}

type GeneratePostResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	PostResponse   *PostGenerationResponse `protobuf:"bytes,1,opt,name=post_response,json=postResponse,proto3" json:"post_response,omitempty"`
	ConversationId string                  `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GeneratePostResponse) Reset() {
	*x = GeneratePostResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePostResponse) ProtoMessage() {}

func (x *GeneratePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePostResponse.ProtoReflect.Descriptor instead.
func (*GeneratePostResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePostResponse) GetPostResponse() *PostGenerationResponse {
	if x != nil {
		return x.PostResponse
	}
	return nil
}

func (x *GeneratePostResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type PostGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Hashtags      []string               `protobuf:"bytes,3,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Metadata      *PostMetadata          `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostGenerationResponse) Reset() {
	*x = PostGenerationResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGenerationResponse) ProtoMessage() {}

func (x *PostGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGenerationResponse.ProtoReflect.Descriptor instead.
func (*PostGenerationResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PostGenerationResponse) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostGenerationResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostGenerationResponse) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

func (x *PostGenerationResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PostGenerationResponse) GetMetadata() *PostMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PostMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tone           string                 `protobuf:"bytes,1,opt,name=tone,proto3" json:"tone,omitempty"`
	Style          string                 `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	GenerationTime int64                  `protobuf:"varint,3,opt,name=generation_time,json=generationTime,proto3" json:"generation_time,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	IsRejection    *bool                  `protobuf:"varint,5,opt,name=is_rejection,json=isRejection,proto3,oneof" json:"is_rejection,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostMetadata) Reset() {
	*x = PostMetadata{}
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMetadata) ProtoMessage() {}

func (x *PostMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMetadata.ProtoReflect.Descriptor instead.
func (*PostMetadata) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *PostMetadata) GetTone() string {
	if x != nil {
		return x.Tone
	}
	return ""
}

func (x *PostMetadata) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *PostMetadata) GetGenerationTime() int64 {
	if x != nil {
		return x.GenerationTime
	}
	return 0
}

func (x *PostMetadata) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PostMetadata) GetIsRejection() bool {
	if x != nil && x.IsRejection != nil {
		return *x.IsRejection
	}
	return false
}

type PostGenerationEvent struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Type          PostGenerationEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=agent.PostGenerationEvent_EventType" json:"type,omitempty"`
	UserId        string                        `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestId     string                        `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          *string                       `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error         *string                       `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Timestamp     int64                         `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostGenerationEvent) Reset() {
	*x = PostGenerationEvent{}
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostGenerationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGenerationEvent) ProtoMessage() {}

func (x *PostGenerationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGenerationEvent.ProtoReflect.Descriptor instead.
func (*PostGenerationEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PostGenerationEvent) GetType() PostGenerationEvent_EventType {
	if x != nil {
		return x.Type
	}
	return PostGenerationEvent_GENERATION_STARTED
}

func (x *PostGenerationEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostGenerationEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PostGenerationEvent) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

func (x *PostGenerationEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *PostGenerationEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetUserCompaniesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCompaniesRequest) Reset() {
	*x = GetUserCompaniesRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCompaniesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCompaniesRequest) ProtoMessage() {}

func (x *GetUserCompaniesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCompaniesRequest.ProtoReflect.Descriptor instead.
func (*GetUserCompaniesRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserCompaniesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserCompaniesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companies     []*Company             `protobuf:"bytes,1,rep,name=companies,proto3" json:"companies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCompaniesResponse) Reset() {
	*x = GetUserCompaniesResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCompaniesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCompaniesResponse) ProtoMessage() {}

func (x *GetUserCompaniesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCompaniesResponse.ProtoReflect.Descriptor instead.
func (*GetUserCompaniesResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserCompaniesResponse) GetCompanies() []*Company {
	if x != nil {
		return x.Companies
	}
	return nil
}

type GetCompanyDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url           *string                `protobuf:"bytes,2,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyDetailsRequest) Reset() {
	*x = GetCompanyDetailsRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyDetailsRequest) ProtoMessage() {}

func (x *GetCompanyDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetCompanyDetailsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCompanyDetailsRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type GetCompanyDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       *Company               `protobuf:"bytes,1,opt,name=company,proto3,oneof" json:"company,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyDetailsResponse) Reset() {
	*x = GetCompanyDetailsResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyDetailsResponse) ProtoMessage() {}

func (x *GetCompanyDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetCompanyDetailsResponse) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

func (x *GetCompanyDetailsResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	FaviconUrl    *string                `protobuf:"bytes,7,opt,name=favicon_url,json=faviconUrl,proto3,oneof" json:"favicon_url,omitempty"`
	LastUpdated   int64                  `protobuf:"varint,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	ScrapedAt     int64                  `protobuf:"varint,9,opt,name=scraped_at,json=scrapedAt,proto3" json:"scraped_at,omitempty"`
	Metadata      *CompanyMetadata       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Company) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Company) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Company) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Company) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Company) GetFaviconUrl() string {
	if x != nil && x.FaviconUrl != nil {
		return *x.FaviconUrl
	}
	return ""
}

func (x *Company) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *Company) GetScrapedAt() int64 {
	if x != nil {
		return x.ScrapedAt
	}
	return 0
}

func (x *Company) GetMetadata() *CompanyMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CompanyMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      *string                `protobuf:"bytes,1,opt,name=keywords,proto3,oneof" json:"keywords,omitempty"`
	Industry      *string                `protobuf:"bytes,2,opt,name=industry,proto3,oneof" json:"industry,omitempty"`
	FaviconUrl    *string                `protobuf:"bytes,3,opt,name=favicon_url,json=faviconUrl,proto3,oneof" json:"favicon_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyMetadata) Reset() {
	*x = CompanyMetadata{}
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyMetadata) ProtoMessage() {}

func (x *CompanyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyMetadata.ProtoReflect.Descriptor instead.
func (*CompanyMetadata) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CompanyMetadata) GetKeywords() string {
	if x != nil && x.Keywords != nil {
		return *x.Keywords
	}
	return ""
}

func (x *CompanyMetadata) GetIndustry() string {
	if x != nil && x.Industry != nil {
		return *x.Industry
	}
	return ""
}

func (x *CompanyMetadata) GetFaviconUrl() string {
	if x != nil && x.FaviconUrl != nil {
		return *x.FaviconUrl
	}
	return ""
}

// Conversation Service Messages
type CreateConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title          *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	InitialMessage *string                `protobuf:"bytes,3,opt,name=initial_message,json=initialMessage,proto3,oneof" json:"initial_message,omitempty"`
	Context        *string                `protobuf:"bytes,4,opt,name=context,proto3,oneof" json:"context,omitempty"` // JSON string
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CreateConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateConversationRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *CreateConversationRequest) GetInitialMessage() string {
	if x != nil && x.InitialMessage != nil {
		return *x.InitialMessage
	}
	return ""
}

func (x *CreateConversationRequest) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

type GetConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *GetConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetUserConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConversationsRequest) Reset() {
	*x = GetUserConversationsRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConversationsRequest) ProtoMessage() {}

func (x *GetUserConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConversationsRequest.ProtoReflect.Descriptor instead.
func (*GetUserConversationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserConversationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserConversationsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type GetUserConversationsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Conversations []*ConversationResponse `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConversationsResponse) Reset() {
	*x = GetUserConversationsResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConversationsResponse) ProtoMessage() {}

func (x *GetUserConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConversationsResponse.ProtoReflect.Descriptor instead.
func (*GetUserConversationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserConversationsResponse) GetConversations() []*ConversationResponse {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type AddMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metadata       *string                `protobuf:"bytes,3,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"` // JSON string
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddMessageRequest) Reset() {
	*x = AddMessageRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMessageRequest) ProtoMessage() {}

func (x *AddMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMessageRequest.ProtoReflect.Descriptor instead.
func (*AddMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *AddMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AddMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddMessageRequest) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

type UpdateConversationTitleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateConversationTitleRequest) Reset() {
	*x = UpdateConversationTitleRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationTitleRequest) ProtoMessage() {}

func (x *UpdateConversationTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationTitleRequest.ProtoReflect.Descriptor instead.
func (*UpdateConversationTitleRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateConversationTitleRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UpdateConversationTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DeleteConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationResponse) Reset() {
	*x = DeleteConversationResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationResponse) ProtoMessage() {}

func (x *DeleteConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationResponse.ProtoReflect.Descriptor instead.
func (*DeleteConversationResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteConversationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConversationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Messages       []*ConversationMessage `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	Context        string                 `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"` // JSON string
	IsActive       bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastMessageAt  int64                  `protobuf:"varint,7,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	MessageCount   int32                  `protobuf:"varint,8,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationResponse) Reset() {
	*x = ConversationResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationResponse) ProtoMessage() {}

func (x *ConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationResponse.ProtoReflect.Descriptor instead.
func (*ConversationResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ConversationResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConversationResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConversationResponse) GetMessages() []*ConversationMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConversationResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ConversationResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ConversationResponse) GetLastMessageAt() int64 {
	if x != nil {
		return x.LastMessageAt
	}
	return 0
}

func (x *ConversationResponse) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

type ConversationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          MessageRole            `protobuf:"varint,1,opt,name=role,proto3,enum=agent.MessageRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *string                `protobuf:"bytes,4,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMessage) Reset() {
	*x = ConversationMessage{}
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessage) ProtoMessage() {}

func (x *ConversationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessage.ProtoReflect.Descriptor instead.
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ConversationMessage) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_USER
}

func (x *ConversationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConversationMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConversationMessage) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

// User Preferences Service Messages
type GetUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferencesRequest) Reset() {
	*x = GetUserPreferencesRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferencesRequest) ProtoMessage() {}

func (x *GetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   *UserPreferences       `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPreferencesRequest) Reset() {
	*x = UpdateUserPreferencesRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferencesRequest) ProtoMessage() {}

func (x *UpdateUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type ResetUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserPreferencesRequest) Reset() {
	*x = ResetUserPreferencesRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPreferencesRequest) ProtoMessage() {}

func (x *ResetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*ResetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ResetUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   *UserPreferences       `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferencesResponse) Reset() {
	*x = UserPreferencesResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferencesResponse) ProtoMessage() {}

func (x *UserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{24}
}

func (x *UserPreferencesResponse) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UserPreferences struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DefaultTone          ToneType               `protobuf:"varint,1,opt,name=default_tone,json=defaultTone,proto3,enum=agent.ToneType" json:"default_tone,omitempty"`
	DefaultStyle         StyleType              `protobuf:"varint,2,opt,name=default_style,json=defaultStyle,proto3,enum=agent.StyleType" json:"default_style,omitempty"`
	PreferredHashtags    []string               `protobuf:"bytes,3,rep,name=preferred_hashtags,json=preferredHashtags,proto3" json:"preferred_hashtags,omitempty"`
	BrandKeywords        []string               `protobuf:"bytes,4,rep,name=brand_keywords,json=brandKeywords,proto3" json:"brand_keywords,omitempty"`
	PlatformSettings     *PlatformSettings      `protobuf:"bytes,5,opt,name=platform_settings,json=platformSettings,proto3" json:"platform_settings,omitempty"`
	ContentPreferences   *ContentPreferences    `protobuf:"bytes,6,opt,name=content_preferences,json=contentPreferences,proto3" json:"content_preferences,omitempty"`
	EnableAutoGeneration bool                   `protobuf:"varint,7,opt,name=enable_auto_generation,json=enableAutoGeneration,proto3" json:"enable_auto_generation,omitempty"`
	DailyPostLimit       int32                  `protobuf:"varint,8,opt,name=daily_post_limit,json=dailyPostLimit,proto3" json:"daily_post_limit,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_proto_agent_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{25}
}

func (x *UserPreferences) GetDefaultTone() ToneType {
	if x != nil {
		return x.DefaultTone
	}
	return ToneType_PROFESSIONAL
}

func (x *UserPreferences) GetDefaultStyle() StyleType {
	if x != nil {
		return x.DefaultStyle
	}
	return StyleType_FORMAL
}

func (x *UserPreferences) GetPreferredHashtags() []string {
	if x != nil {
		return x.PreferredHashtags
	}
	return nil
}

func (x *UserPreferences) GetBrandKeywords() []string {
	if x != nil {
		return x.BrandKeywords
	}
	return nil
}

func (x *UserPreferences) GetPlatformSettings() *PlatformSettings {
	if x != nil {
		return x.PlatformSettings
	}
	return nil
}

func (x *UserPreferences) GetContentPreferences() *ContentPreferences {
	if x != nil {
		return x.ContentPreferences
	}
	return nil
}

func (x *UserPreferences) GetEnableAutoGeneration() bool {
	if x != nil {
		return x.EnableAutoGeneration
	}
	return false
}

func (x *UserPreferences) GetDailyPostLimit() int32 {
	if x != nil {
		return x.DailyPostLimit
	}
	return 0
}

type PlatformSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Twitter       *TwitterSettings       `protobuf:"bytes,1,opt,name=twitter,proto3" json:"twitter,omitempty"`
	Instagram     *InstagramSettings     `protobuf:"bytes,2,opt,name=instagram,proto3" json:"instagram,omitempty"`
	Facebook      *FacebookSettings      `protobuf:"bytes,3,opt,name=facebook,proto3" json:"facebook,omitempty"`
	Linkedin      *LinkedinSettings      `protobuf:"bytes,4,opt,name=linkedin,proto3" json:"linkedin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformSettings) Reset() {
	*x = PlatformSettings{}
	mi := &file_proto_agent_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformSettings) ProtoMessage() {}

func (x *PlatformSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformSettings.ProtoReflect.Descriptor instead.
func (*PlatformSettings) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{26}
}

func (x *PlatformSettings) GetTwitter() *TwitterSettings {
	if x != nil {
		return x.Twitter
	}
	return nil
}

func (x *PlatformSettings) GetInstagram() *InstagramSettings {
	if x != nil {
		return x.Instagram
	}
	return nil
}

func (x *PlatformSettings) GetFacebook() *FacebookSettings {
	if x != nil {
		return x.Facebook
	}
	return nil
}

func (x *PlatformSettings) GetLinkedin() *LinkedinSettings {
	if x != nil {
		return x.Linkedin
	}
	return nil
}

type TwitterSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxLength       *int32                 `protobuf:"varint,1,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	UseHashtags     *bool                  `protobuf:"varint,2,opt,name=use_hashtags,json=useHashtags,proto3,oneof" json:"use_hashtags,omitempty"`
	IncludeMentions *bool                  `protobuf:"varint,3,opt,name=include_mentions,json=includeMentions,proto3,oneof" json:"include_mentions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TwitterSettings) Reset() {
	*x = TwitterSettings{}
	mi := &file_proto_agent_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwitterSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitterSettings) ProtoMessage() {}

func (x *TwitterSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitterSettings.ProtoReflect.Descriptor instead.
func (*TwitterSettings) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{27}
}

func (x *TwitterSettings) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

func (x *TwitterSettings) GetUseHashtags() bool {
	if x != nil && x.UseHashtags != nil {
		return *x.UseHashtags
	}
	return false
}

func (x *TwitterSettings) GetIncludeMentions() bool {
	if x != nil && x.IncludeMentions != nil {
		return *x.IncludeMentions
	}
	return false
}

type InstagramSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UseHashtags   *bool                  `protobuf:"varint,1,opt,name=use_hashtags,json=useHashtags,proto3,oneof" json:"use_hashtags,omitempty"`
	HashtagCount  *int32                 `protobuf:"varint,2,opt,name=hashtag_count,json=hashtagCount,proto3,oneof" json:"hashtag_count,omitempty"`
	IncludeEmojis *bool                  `protobuf:"varint,3,opt,name=include_emojis,json=includeEmojis,proto3,oneof" json:"include_emojis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstagramSettings) Reset() {
	*x = InstagramSettings{}
	mi := &file_proto_agent_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstagramSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstagramSettings) ProtoMessage() {}

func (x *InstagramSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstagramSettings.ProtoReflect.Descriptor instead.
func (*InstagramSettings) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{28}
}

func (x *InstagramSettings) GetUseHashtags() bool {
	if x != nil && x.UseHashtags != nil {
		return *x.UseHashtags
	}
	return false
}

func (x *InstagramSettings) GetHashtagCount() int32 {
	if x != nil && x.HashtagCount != nil {
		return *x.HashtagCount
	}
	return 0
}

func (x *InstagramSettings) GetIncludeEmojis() bool {
	if x != nil && x.IncludeEmojis != nil {
		return *x.IncludeEmojis
	}
	return false
}

type FacebookSettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IncludeCallToAction *bool                  `protobuf:"varint,1,opt,name=include_call_to_action,json=includeCallToAction,proto3,oneof" json:"include_call_to_action,omitempty"`
	UseEmojis           *bool                  `protobuf:"varint,2,opt,name=use_emojis,json=useEmojis,proto3,oneof" json:"use_emojis,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FacebookSettings) Reset() {
	*x = FacebookSettings{}
	mi := &file_proto_agent_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacebookSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacebookSettings) ProtoMessage() {}

func (x *FacebookSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacebookSettings.ProtoReflect.Descriptor instead.
func (*FacebookSettings) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{29}
}

func (x *FacebookSettings) GetIncludeCallToAction() bool {
	if x != nil && x.IncludeCallToAction != nil {
		return *x.IncludeCallToAction
	}
	return false
}

func (x *FacebookSettings) GetUseEmojis() bool {
	if x != nil && x.UseEmojis != nil {
		return *x.UseEmojis
	}
	return false
}

type LinkedinSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProfessionalTone     *bool                  `protobuf:"varint,1,opt,name=professional_tone,json=professionalTone,proto3,oneof" json:"professional_tone,omitempty"`
	IncludeIndustryTerms *bool                  `protobuf:"varint,2,opt,name=include_industry_terms,json=includeIndustryTerms,proto3,oneof" json:"include_industry_terms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LinkedinSettings) Reset() {
	*x = LinkedinSettings{}
	mi := &file_proto_agent_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedinSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedinSettings) ProtoMessage() {}

func (x *LinkedinSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedinSettings.ProtoReflect.Descriptor instead.
func (*LinkedinSettings) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{30}
}

func (x *LinkedinSettings) GetProfessionalTone() bool {
	if x != nil && x.ProfessionalTone != nil {
		return *x.ProfessionalTone
	}
	return false
}

func (x *LinkedinSettings) GetIncludeIndustryTerms() bool {
	if x != nil && x.IncludeIndustryTerms != nil {
		return *x.IncludeIndustryTerms
	}
	return false
}

type ContentPreferences struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetAudience    *string                `protobuf:"bytes,1,opt,name=target_audience,json=targetAudience,proto3,oneof" json:"target_audience,omitempty"`
	IndustryFocus     []string               `protobuf:"bytes,2,rep,name=industry_focus,json=industryFocus,proto3" json:"industry_focus,omitempty"`
	ContentCategories []string               `protobuf:"bytes,3,rep,name=content_categories,json=contentCategories,proto3" json:"content_categories,omitempty"`
	AvoidTopics       []string               `protobuf:"bytes,4,rep,name=avoid_topics,json=avoidTopics,proto3" json:"avoid_topics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContentPreferences) Reset() {
	*x = ContentPreferences{}
	mi := &file_proto_agent_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPreferences) ProtoMessage() {}

func (x *ContentPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPreferences.ProtoReflect.Descriptor instead.
func (*ContentPreferences) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{31}
}

func (x *ContentPreferences) GetTargetAudience() string {
	if x != nil && x.TargetAudience != nil {
		return *x.TargetAudience
	}
	return ""
}

func (x *ContentPreferences) GetIndustryFocus() []string {
	if x != nil {
		return x.IndustryFocus
	}
	return nil
}

func (x *ContentPreferences) GetContentCategories() []string {
	if x != nil {
		return x.ContentCategories
	}
	return nil
}

func (x *ContentPreferences) GetAvoidTopics() []string {
	if x != nil {
		return x.AvoidTopics
	}
	return nil
}

var File_proto_agent_agent_proto protoreflect.FileDescriptor

const file_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/agent/agent.proto\x12\x05agent\"\x81\x03\n" +
	"\x13GeneratePostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x0fconversation_id\x18\x02 \x01(\tH\x00R\x0econversationId\x88\x01\x01\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\"\n" +
	"\n" +
	"company_id\x18\x04 \x01(\tH\x01R\tcompanyId\x88\x01\x01\x12$\n" +
	"\vcompany_url\x18\x05 \x01(\tH\x02R\n" +
	"companyUrl\x88\x01\x01\x12(\n" +
	"\rcustom_prompt\x18\x06 \x01(\tH\x03R\fcustomPrompt\x88\x01\x01\x125\n" +
	"\x14include_company_data\x18\a \x01(\bH\x04R\x12includeCompanyData\x88\x01\x01B\x12\n" +
	"\x10_conversation_idB\r\n" +
	"\v_company_idB\x0e\n" +
	"\f_company_urlB\x10\n" +
	"\x0e_custom_promptB\x17\n" +
	"\x15_include_company_data\"\x83\x01\n" +
	"\x14GeneratePostResponse\x12B\n" +
	"\rpost_response\x18\x01 \x01(\v2\x1d.agent.PostGenerationResponseR\fpostResponse\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"\xb4\x01\n" +
	"\x16PostGenerationResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bhashtags\x18\x03 \x03(\tR\bhashtags\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12/\n" +
	"\bmetadata\x18\x05 \x01(\v2\x13.agent.PostMetadataR\bmetadata\"\xb0\x01\n" +
	"\fPostMetadata\x12\x12\n" +
	"\x04tone\x18\x01 \x01(\tR\x04tone\x12\x14\n" +
	"\x05style\x18\x02 \x01(\tR\x05style\x12'\n" +
	"\x0fgeneration_time\x18\x03 \x01(\x03R\x0egenerationTime\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12&\n" +
	"\fis_rejection\x18\x05 \x01(\bH\x00R\visRejection\x88\x01\x01B\x0f\n" +
	"\r_is_rejection\"\xda\x02\n" +
	"\x13PostGenerationEvent\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.agent.PostGenerationEvent.EventTypeR\x04type\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x17\n" +
	"\x04data\x18\x04 \x01(\tH\x00R\x04data\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x05 \x01(\tH\x01R\x05error\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"l\n" +
	"\tEventType\x12\x16\n" +
	"\x12GENERATION_STARTED\x10\x00\x12\x17\n" +
	"\x13GENERATION_PROGRESS\x10\x01\x12\x18\n" +
	"\x14GENERATION_COMPLETED\x10\x02\x12\x14\n" +
	"\x10GENERATION_ERROR\x10\x03B\a\n" +
	"\x05_dataB\b\n" +
	"\x06_error\"2\n" +
	"\x17GetUserCompaniesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x18GetUserCompaniesResponse\x12,\n" +
	"\tcompanies\x18\x01 \x03(\v2\x0e.agent.CompanyR\tcompanies\"R\n" +
	"\x18GetCompanyDetailsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x03url\x18\x02 \x01(\tH\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"\x81\x01\n" +
	"\x19GetCompanyDetailsResponse\x12-\n" +
	"\acompany\x18\x01 \x01(\v2\x0e.agent.CompanyH\x00R\acompany\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x01R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_companyB\n" +
	"\n" +
	"\b_message\"\xc0\x02\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12$\n" +
	"\vfavicon_url\x18\a \x01(\tH\x00R\n" +
	"faviconUrl\x88\x01\x01\x12!\n" +
	"\flast_updated\x18\b \x01(\x03R\vlastUpdated\x12\x1d\n" +
	"\n" +
	"scraped_at\x18\t \x01(\x03R\tscrapedAt\x122\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x16.agent.CompanyMetadataR\bmetadataB\x0e\n" +
	"\f_favicon_url\"\xa3\x01\n" +
	"\x0fCompanyMetadata\x12\x1f\n" +
	"\bkeywords\x18\x01 \x01(\tH\x00R\bkeywords\x88\x01\x01\x12\x1f\n" +
	"\bindustry\x18\x02 \x01(\tH\x01R\bindustry\x88\x01\x01\x12$\n" +
	"\vfavicon_url\x18\x03 \x01(\tH\x02R\n" +
	"faviconUrl\x88\x01\x01B\v\n" +
	"\t_keywordsB\v\n" +
	"\t_industryB\x0e\n" +
	"\f_favicon_url\"\xc6\x01\n" +
	"\x19CreateConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12,\n" +
	"\x0finitial_message\x18\x03 \x01(\tH\x01R\x0einitialMessage\x88\x01\x01\x12\x1d\n" +
	"\acontext\x18\x04 \x01(\tH\x02R\acontext\x88\x01\x01B\b\n" +
	"\x06_titleB\x12\n" +
	"\x10_initial_messageB\n" +
	"\n" +
	"\b_context\"A\n" +
	"\x16GetConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"[\n" +
	"\x1bGetUserConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"a\n" +
	"\x1cGetUserConversationsResponse\x12A\n" +
	"\rconversations\x18\x01 \x03(\v2\x1b.agent.ConversationResponseR\rconversations\"\x84\x01\n" +
	"\x11AddMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\bmetadata\x18\x03 \x01(\tH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"_\n" +
	"\x1eUpdateConversationTitleRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"D\n" +
	"\x19DeleteConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"6\n" +
	"\x1aDeleteConversationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xaa\x02\n" +
	"\x14ConversationResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x126\n" +
	"\bmessages\x18\x04 \x03(\v2\x1a.agent.ConversationMessageR\bmessages\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontext\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12&\n" +
	"\x0flast_message_at\x18\a \x01(\x03R\rlastMessageAt\x12#\n" +
	"\rmessage_count\x18\b \x01(\x05R\fmessageCount\"\xa3\x01\n" +
	"\x13ConversationMessage\x12&\n" +
	"\x04role\x18\x01 \x01(\x0e2\x12.agent.MessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\bmetadata\x18\x04 \x01(\tH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"4\n" +
	"\x19GetUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"q\n" +
	"\x1cUpdateUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x128\n" +
	"\vpreferences\x18\x02 \x01(\v2\x16.agent.UserPreferencesR\vpreferences\"6\n" +
	"\x1bResetUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"S\n" +
	"\x17UserPreferencesResponse\x128\n" +
	"\vpreferences\x18\x01 \x01(\v2\x16.agent.UserPreferencesR\vpreferences\"\xc4\x03\n" +
	"\x0fUserPreferences\x122\n" +
	"\fdefault_tone\x18\x01 \x01(\x0e2\x0f.agent.ToneTypeR\vdefaultTone\x125\n" +
	"\rdefault_style\x18\x02 \x01(\x0e2\x10.agent.StyleTypeR\fdefaultStyle\x12-\n" +
	"\x12preferred_hashtags\x18\x03 \x03(\tR\x11preferredHashtags\x12%\n" +
	"\x0ebrand_keywords\x18\x04 \x03(\tR\rbrandKeywords\x12D\n" +
	"\x11platform_settings\x18\x05 \x01(\v2\x17.agent.PlatformSettingsR\x10platformSettings\x12J\n" +
	"\x13content_preferences\x18\x06 \x01(\v2\x19.agent.ContentPreferencesR\x12contentPreferences\x124\n" +
	"\x16enable_auto_generation\x18\a \x01(\bR\x14enableAutoGeneration\x12(\n" +
	"\x10daily_post_limit\x18\b \x01(\x05R\x0edailyPostLimit\"\xe6\x01\n" +
	"\x10PlatformSettings\x120\n" +
	"\atwitter\x18\x01 \x01(\v2\x16.agent.TwitterSettingsR\atwitter\x126\n" +
	"\tinstagram\x18\x02 \x01(\v2\x18.agent.InstagramSettingsR\tinstagram\x123\n" +
	"\bfacebook\x18\x03 \x01(\v2\x17.agent.FacebookSettingsR\bfacebook\x123\n" +
	"\blinkedin\x18\x04 \x01(\v2\x17.agent.LinkedinSettingsR\blinkedin\"\xc2\x01\n" +
	"\x0fTwitterSettings\x12\"\n" +
	"\n" +
	"max_length\x18\x01 \x01(\x05H\x00R\tmaxLength\x88\x01\x01\x12&\n" +
	"\fuse_hashtags\x18\x02 \x01(\bH\x01R\vuseHashtags\x88\x01\x01\x12.\n" +
	"\x10include_mentions\x18\x03 \x01(\bH\x02R\x0fincludeMentions\x88\x01\x01B\r\n" +
	"\v_max_lengthB\x0f\n" +
	"\r_use_hashtagsB\x13\n" +
	"\x11_include_mentions\"\xc7\x01\n" +
	"\x11InstagramSettings\x12&\n" +
	"\fuse_hashtags\x18\x01 \x01(\bH\x00R\vuseHashtags\x88\x01\x01\x12(\n" +
	"\rhashtag_count\x18\x02 \x01(\x05H\x01R\fhashtagCount\x88\x01\x01\x12*\n" +
	"\x0einclude_emojis\x18\x03 \x01(\bH\x02R\rincludeEmojis\x88\x01\x01B\x0f\n" +
	"\r_use_hashtagsB\x10\n" +
	"\x0e_hashtag_countB\x11\n" +
	"\x0f_include_emojis\"\x9a\x01\n" +
	"\x10FacebookSettings\x128\n" +
	"\x16include_call_to_action\x18\x01 \x01(\bH\x00R\x13includeCallToAction\x88\x01\x01\x12\"\n" +
	"\n" +
	"use_emojis\x18\x02 \x01(\bH\x01R\tuseEmojis\x88\x01\x01B\x19\n" +
	"\x17_include_call_to_actionB\r\n" +
	"\v_use_emojis\"\xb0\x01\n" +
	"\x10LinkedinSettings\x120\n" +
	"\x11professional_tone\x18\x01 \x01(\bH\x00R\x10professionalTone\x88\x01\x01\x129\n" +
	"\x16include_industry_terms\x18\x02 \x01(\bH\x01R\x14includeIndustryTerms\x88\x01\x01B\x14\n" +
	"\x12_professional_toneB\x19\n" +
	"\x17_include_industry_terms\"\xcf\x01\n" +
	"\x12ContentPreferences\x12,\n" +
	"\x0ftarget_audience\x18\x01 \x01(\tH\x00R\x0etargetAudience\x88\x01\x01\x12%\n" +
	"\x0eindustry_focus\x18\x02 \x03(\tR\rindustryFocus\x12-\n" +
	"\x12content_categories\x18\x03 \x03(\tR\x11contentCategories\x12!\n" +
	"\favoid_topics\x18\x04 \x03(\tR\vavoidTopicsB\x12\n" +
	"\x10_target_audience*H\n" +
	"\x0eSocialPlatform\x12\v\n" +
	"\aTWITTER\x10\x00\x12\r\n" +
	"\tINSTAGRAM\x10\x01\x12\f\n" +
	"\bFACEBOOK\x10\x02\x12\f\n" +
	"\bLINKEDIN\x10\x03*\xc0\x01\n" +
	"\bToneType\x12\x10\n" +
	"\fPROFESSIONAL\x10\x00\x12\n" +
	"\n" +
	"\x06CASUAL\x10\x01\x12\f\n" +
	"\bFRIENDLY\x10\x02\x12\x11\n" +
	"\rAUTHORITATIVE\x10\x03\x12\f\n" +
	"\bHUMOROUS\x10\x04\x12\x11\n" +
	"\rINSPIRATIONAL\x10\x05\x12\t\n" +
	"\x05WITTY\x10\x06\x12\t\n" +
	"\x05FUNNY\x10\a\x12\r\n" +
	"\tSARCASTIC\x10\b\x12\x10\n" +
	"\fENTHUSIASTIC\x10\t\x12\x0e\n" +
	"\n" +
	"EMPATHETIC\x10\n" +
	"\x12\r\n" +
	"\tCONFIDENT\x10\v*i\n" +
	"\tStyleType\x12\n" +
	"\n" +
	"\x06FORMAL\x10\x00\x12\x12\n" +
	"\x0eCONVERSATIONAL\x10\x01\x12\x10\n" +
	"\fSTORYTELLING\x10\x02\x12\x0f\n" +
	"\vEDUCATIONAL\x10\x03\x12\x0f\n" +
	"\vPROMOTIONAL\x10\x04\x12\b\n" +
	"\x04NEWS\x10\x05*2\n" +
	"\vMessageRole\x12\b\n" +
	"\x04USER\x10\x00\x12\r\n" +
	"\tASSISTANT\x10\x01\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x022\xd4\x02\n" +
	"\fAgentService\x12G\n" +
	"\fGeneratePost\x12\x1a.agent.GeneratePostRequest\x1a\x1b.agent.GeneratePostResponse\x12N\n" +
	"\x12GeneratePostStream\x12\x1a.agent.GeneratePostRequest\x1a\x1a.agent.PostGenerationEvent0\x01\x12S\n" +
	"\x10GetUserCompanies\x12\x1e.agent.GetUserCompaniesRequest\x1a\x1f.agent.GetUserCompaniesResponse\x12V\n" +
	"\x11GetCompanyDetails\x12\x1f.agent.GetCompanyDetailsRequest\x1a .agent.GetCompanyDetailsResponse2\x99\x04\n" +
	"\x13ConversationService\x12S\n" +
	"\x12CreateConversation\x12 .agent.CreateConversationRequest\x1a\x1b.agent.ConversationResponse\x12M\n" +
	"\x0fGetConversation\x12\x1d.agent.GetConversationRequest\x1a\x1b.agent.ConversationResponse\x12_\n" +
	"\x14GetUserConversations\x12\".agent.GetUserConversationsRequest\x1a#.agent.GetUserConversationsResponse\x12C\n" +
	"\n" +
	"AddMessage\x12\x18.agent.AddMessageRequest\x1a\x1b.agent.ConversationResponse\x12]\n" +
	"\x17UpdateConversationTitle\x12%.agent.UpdateConversationTitleRequest\x1a\x1b.agent.ConversationResponse\x12Y\n" +
	"\x12DeleteConversation\x12 .agent.DeleteConversationRequest\x1a!.agent.DeleteConversationResponse2\xaa\x02\n" +
	"\x16UserPreferencesService\x12V\n" +
	"\x12GetUserPreferences\x12 .agent.GetUserPreferencesRequest\x1a\x1e.agent.UserPreferencesResponse\x12\\\n" +
	"\x15UpdateUserPreferences\x12#.agent.UpdateUserPreferencesRequest\x1a\x1e.agent.UserPreferencesResponse\x12Z\n" +
	"\x14ResetUserPreferences\x12\".agent.ResetUserPreferencesRequest\x1a\x1e.agent.UserPreferencesResponseB?Z=github.com/ByteSurgeonAmos/go-auth-stream/proto/agent;agentpbb\x06proto3"

var (
	file_proto_agent_agent_proto_rawDescOnce sync.Once
	file_proto_agent_agent_proto_rawDescData []byte
)

func file_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)))
	})
	return file_proto_agent_agent_proto_rawDescData
}

var file_proto_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_agent_agent_proto_goTypes = []any{
	(SocialPlatform)(0),                    // 0: agent.SocialPlatform
	(ToneType)(0),                          // 1: agent.ToneType
	(StyleType)(0),                         // 2: agent.StyleType
	(MessageRole)(0),                       // 3: agent.MessageRole
	(PostGenerationEvent_EventType)(0),     // 4: agent.PostGenerationEvent.EventType
	(*GeneratePostRequest)(nil),            // 5: agent.GeneratePostRequest
	(*GeneratePostResponse)(nil),           // 6: agent.GeneratePostResponse
	(*PostGenerationResponse)(nil),         // 7: agent.PostGenerationResponse
	(*PostMetadata)(nil),                   // 8: agent.PostMetadata
	(*PostGenerationEvent)(nil),            // 9: agent.PostGenerationEvent
	(*GetUserCompaniesRequest)(nil),        // 10: agent.GetUserCompaniesRequest
	(*GetUserCompaniesResponse)(nil),       // 11: agent.GetUserCompaniesResponse
	(*GetCompanyDetailsRequest)(nil),       // 12: agent.GetCompanyDetailsRequest
	(*GetCompanyDetailsResponse)(nil),      // 13: agent.GetCompanyDetailsResponse
	(*Company)(nil),                        // 14: agent.Company
	(*CompanyMetadata)(nil),                // 15: agent.CompanyMetadata
	(*CreateConversationRequest)(nil),      // 16: agent.CreateConversationRequest
	(*GetConversationRequest)(nil),         // 17: agent.GetConversationRequest
	(*GetUserConversationsRequest)(nil),    // 18: agent.GetUserConversationsRequest
	(*GetUserConversationsResponse)(nil),   // 19: agent.GetUserConversationsResponse
	(*AddMessageRequest)(nil),              // 20: agent.AddMessageRequest
	(*UpdateConversationTitleRequest)(nil), // 21: agent.UpdateConversationTitleRequest
	(*DeleteConversationRequest)(nil),      // 22: agent.DeleteConversationRequest
	(*DeleteConversationResponse)(nil),     // 23: agent.DeleteConversationResponse
	(*ConversationResponse)(nil),           // 24: agent.ConversationResponse
	(*ConversationMessage)(nil),            // 25: agent.ConversationMessage
	(*GetUserPreferencesRequest)(nil),      // 26: agent.GetUserPreferencesRequest
	(*UpdateUserPreferencesRequest)(nil),   // 27: agent.UpdateUserPreferencesRequest
	(*ResetUserPreferencesRequest)(nil),    // 28: agent.ResetUserPreferencesRequest
	(*UserPreferencesResponse)(nil),        // 29: agent.UserPreferencesResponse
	(*UserPreferences)(nil),                // 30: agent.UserPreferences
	(*PlatformSettings)(nil),               // 31: agent.PlatformSettings
	(*TwitterSettings)(nil),                // 32: agent.TwitterSettings
	(*InstagramSettings)(nil),              // 33: agent.InstagramSettings
	(*FacebookSettings)(nil),               // 34: agent.FacebookSettings
	(*LinkedinSettings)(nil),               // 35: agent.LinkedinSettings
	(*ContentPreferences)(nil),             // 36: agent.ContentPreferences
}
var file_proto_agent_agent_proto_depIdxs = []int32{
	7,  // 0: agent.GeneratePostResponse.post_response:type_name -> agent.PostGenerationResponse
	8,  // 1: agent.PostGenerationResponse.metadata:type_name -> agent.PostMetadata
	4,  // 2: agent.PostGenerationEvent.type:type_name -> agent.PostGenerationEvent.EventType
	14, // 3: agent.GetUserCompaniesResponse.companies:type_name -> agent.Company
	14, // 4: agent.GetCompanyDetailsResponse.company:type_name -> agent.Company
	15, // 5: agent.Company.metadata:type_name -> agent.CompanyMetadata
	24, // 6: agent.GetUserConversationsResponse.conversations:type_name -> agent.ConversationResponse
	25, // 7: agent.ConversationResponse.messages:type_name -> agent.ConversationMessage
	3,  // 8: agent.ConversationMessage.role:type_name -> agent.MessageRole
	30, // 9: agent.UpdateUserPreferencesRequest.preferences:type_name -> agent.UserPreferences
	30, // 10: agent.UserPreferencesResponse.preferences:type_name -> agent.UserPreferences
	1,  // 11: agent.UserPreferences.default_tone:type_name -> agent.ToneType
	2,  // 12: agent.UserPreferences.default_style:type_name -> agent.StyleType
	31, // 13: agent.UserPreferences.platform_settings:type_name -> agent.PlatformSettings
	36, // 14: agent.UserPreferences.content_preferences:type_name -> agent.ContentPreferences
	32, // 15: agent.PlatformSettings.twitter:type_name -> agent.TwitterSettings
	33, // 16: agent.PlatformSettings.instagram:type_name -> agent.InstagramSettings
	34, // 17: agent.PlatformSettings.facebook:type_name -> agent.FacebookSettings
	35, // 18: agent.PlatformSettings.linkedin:type_name -> agent.LinkedinSettings
	5,  // 19: agent.AgentService.GeneratePost:input_type -> agent.GeneratePostRequest
	5,  // 20: agent.AgentService.GeneratePostStream:input_type -> agent.GeneratePostRequest
	10, // 21: agent.AgentService.GetUserCompanies:input_type -> agent.GetUserCompaniesRequest
	12, // 22: agent.AgentService.GetCompanyDetails:input_type -> agent.GetCompanyDetailsRequest
	16, // 23: agent.ConversationService.CreateConversation:input_type -> agent.CreateConversationRequest
	17, // 24: agent.ConversationService.GetConversation:input_type -> agent.GetConversationRequest
	18, // 25: agent.ConversationService.GetUserConversations:input_type -> agent.GetUserConversationsRequest
	20, // 26: agent.ConversationService.AddMessage:input_type -> agent.AddMessageRequest
	21, // 27: agent.ConversationService.UpdateConversationTitle:input_type -> agent.UpdateConversationTitleRequest
	22, // 28: agent.ConversationService.DeleteConversation:input_type -> agent.DeleteConversationRequest
	26, // 29: agent.UserPreferencesService.GetUserPreferences:input_type -> agent.GetUserPreferencesRequest
	27, // 30: agent.UserPreferencesService.UpdateUserPreferences:input_type -> agent.UpdateUserPreferencesRequest
	28, // 31: agent.UserPreferencesService.ResetUserPreferences:input_type -> agent.ResetUserPreferencesRequest
	6,  // 32: agent.AgentService.GeneratePost:output_type -> agent.GeneratePostResponse
	9,  // 33: agent.AgentService.GeneratePostStream:output_type -> agent.PostGenerationEvent
	11, // 34: agent.AgentService.GetUserCompanies:output_type -> agent.GetUserCompaniesResponse
	13, // 35: agent.AgentService.GetCompanyDetails:output_type -> agent.GetCompanyDetailsResponse
	24, // 36: agent.ConversationService.CreateConversation:output_type -> agent.ConversationResponse
	24, // 37: agent.ConversationService.GetConversation:output_type -> agent.ConversationResponse
	19, // 38: agent.ConversationService.GetUserConversations:output_type -> agent.GetUserConversationsResponse
	24, // 39: agent.ConversationService.AddMessage:output_type -> agent.ConversationResponse
	24, // 40: agent.ConversationService.UpdateConversationTitle:output_type -> agent.ConversationResponse
	23, // 41: agent.ConversationService.DeleteConversation:output_type -> agent.DeleteConversationResponse
	29, // 42: agent.UserPreferencesService.GetUserPreferences:output_type -> agent.UserPreferencesResponse
	29, // 43: agent.UserPreferencesService.UpdateUserPreferences:output_type -> agent.UserPreferencesResponse
	29, // 44: agent.UserPreferencesService.ResetUserPreferences:output_type -> agent.UserPreferencesResponse
	32, // [32:45] is the sub-list for method output_type
	19, // [19:32] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_agent_agent_proto_init() }
func file_proto_agent_agent_proto_init() {
	if File_proto_agent_agent_proto != nil {
		return
	}
	file_proto_agent_agent_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[13].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[15].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[20].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[27].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[28].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[29].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[30].OneofWrappers = []any{}
	file_proto_agent_agent_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_agent_proto = out.File
	file_proto_agent_agent_proto_goTypes = nil
	file_proto_agent_agent_proto_depIdxs = nil
}
