// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/agent/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_GeneratePost_FullMethodName       = "/agent.AgentService/GeneratePost"
	AgentService_GeneratePostStream_FullMethodName = "/agent.AgentService/GeneratePostStream"
	AgentService_GetUserCompanies_FullMethodName   = "/agent.AgentService/GetUserCompanies"
	AgentService_GetCompanyDetails_FullMethodName  = "/agent.AgentService/GetCompanyDetails"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Generate post with conversation context
	GeneratePost(ctx context.Context, in *GeneratePostRequest, opts ...grpc.CallOption) (*GeneratePostResponse, error)
	// Stream post generation with real-time updates
	GeneratePostStream(ctx context.Context, in *GeneratePostRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PostGenerationEvent], error)
	// Get user companies
	GetUserCompanies(ctx context.Context, in *GetUserCompaniesRequest, opts ...grpc.CallOption) (*GetUserCompaniesResponse, error)
	// Get company details
	GetCompanyDetails(ctx context.Context, in *GetCompanyDetailsRequest, opts ...grpc.CallOption) (*GetCompanyDetailsResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GeneratePost(ctx context.Context, in *GeneratePostRequest, opts ...grpc.CallOption) (*GeneratePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePostResponse)
	err := c.cc.Invoke(ctx, AgentService_GeneratePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GeneratePostStream(ctx context.Context, in *GeneratePostRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PostGenerationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_GeneratePostStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GeneratePostRequest, PostGenerationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GeneratePostStreamClient = grpc.ServerStreamingClient[PostGenerationEvent]

func (c *agentServiceClient) GetUserCompanies(ctx context.Context, in *GetUserCompaniesRequest, opts ...grpc.CallOption) (*GetUserCompaniesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCompaniesResponse)
	err := c.cc.Invoke(ctx, AgentService_GetUserCompanies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetCompanyDetails(ctx context.Context, in *GetCompanyDetailsRequest, opts ...grpc.CallOption) (*GetCompanyDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompanyDetailsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetCompanyDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// Generate post with conversation context
	GeneratePost(context.Context, *GeneratePostRequest) (*GeneratePostResponse, error)
	// Stream post generation with real-time updates
	GeneratePostStream(*GeneratePostRequest, grpc.ServerStreamingServer[PostGenerationEvent]) error
	// Get user companies
	GetUserCompanies(context.Context, *GetUserCompaniesRequest) (*GetUserCompaniesResponse, error)
	// Get company details
	GetCompanyDetails(context.Context, *GetCompanyDetailsRequest) (*GetCompanyDetailsResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) GeneratePost(context.Context, *GeneratePostRequest) (*GeneratePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePost not implemented")
}
func (UnimplementedAgentServiceServer) GeneratePostStream(*GeneratePostRequest, grpc.ServerStreamingServer[PostGenerationEvent]) error {
	return status.Errorf(codes.Unimplemented, "method GeneratePostStream not implemented")
}
func (UnimplementedAgentServiceServer) GetUserCompanies(context.Context, *GetUserCompaniesRequest) (*GetUserCompaniesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCompanies not implemented")
}
func (UnimplementedAgentServiceServer) GetCompanyDetails(context.Context, *GetCompanyDetailsRequest) (*GetCompanyDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanyDetails not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_GeneratePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GeneratePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GeneratePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GeneratePost(ctx, req.(*GeneratePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GeneratePostStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GeneratePostRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).GeneratePostStream(m, &grpc.GenericServerStream[GeneratePostRequest, PostGenerationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GeneratePostStreamServer = grpc.ServerStreamingServer[PostGenerationEvent]

func _AgentService_GetUserCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCompaniesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetUserCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetUserCompanies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetUserCompanies(ctx, req.(*GetUserCompaniesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetCompanyDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetCompanyDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetCompanyDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetCompanyDetails(ctx, req.(*GetCompanyDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePost",
			Handler:    _AgentService_GeneratePost_Handler,
		},
		{
			MethodName: "GetUserCompanies",
			Handler:    _AgentService_GetUserCompanies_Handler,
		},
		{
			MethodName: "GetCompanyDetails",
			Handler:    _AgentService_GetCompanyDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GeneratePostStream",
			Handler:       _AgentService_GeneratePostStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent/agent.proto",
}

const (
	ConversationService_CreateConversation_FullMethodName      = "/agent.ConversationService/CreateConversation"
	ConversationService_GetConversation_FullMethodName         = "/agent.ConversationService/GetConversation"
	ConversationService_GetUserConversations_FullMethodName    = "/agent.ConversationService/GetUserConversations"
	ConversationService_AddMessage_FullMethodName              = "/agent.ConversationService/AddMessage"
	ConversationService_UpdateConversationTitle_FullMethodName = "/agent.ConversationService/UpdateConversationTitle"
	ConversationService_DeleteConversation_FullMethodName      = "/agent.ConversationService/DeleteConversation"
)

// ConversationServiceClient is the client API for ConversationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationServiceClient interface {
	// Create new conversation
	CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*ConversationResponse, error)
	// Get conversation by ID
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*ConversationResponse, error)
	// Get user conversations
	GetUserConversations(ctx context.Context, in *GetUserConversationsRequest, opts ...grpc.CallOption) (*GetUserConversationsResponse, error)
	// Add message to conversation
	AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*ConversationResponse, error)
	// Update conversation title
	UpdateConversationTitle(ctx context.Context, in *UpdateConversationTitleRequest, opts ...grpc.CallOption) (*ConversationResponse, error)
	// Delete conversation
	DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error)
}

type conversationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationServiceClient(cc grpc.ClientConnInterface) ConversationServiceClient {
	return &conversationServiceClient{cc}
}

func (c *conversationServiceClient) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*ConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationResponse)
	err := c.cc.Invoke(ctx, ConversationService_CreateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*ConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationResponse)
	err := c.cc.Invoke(ctx, ConversationService_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetUserConversations(ctx context.Context, in *GetUserConversationsRequest, opts ...grpc.CallOption) (*GetUserConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserConversationsResponse)
	err := c.cc.Invoke(ctx, ConversationService_GetUserConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*ConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationResponse)
	err := c.cc.Invoke(ctx, ConversationService_AddMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateConversationTitle(ctx context.Context, in *UpdateConversationTitleRequest, opts ...grpc.CallOption) (*ConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversationResponse)
	err := c.cc.Invoke(ctx, ConversationService_UpdateConversationTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConversationResponse)
	err := c.cc.Invoke(ctx, ConversationService_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationServiceServer is the server API for ConversationService service.
// All implementations must embed UnimplementedConversationServiceServer
// for forward compatibility.
type ConversationServiceServer interface {
	// Create new conversation
	CreateConversation(context.Context, *CreateConversationRequest) (*ConversationResponse, error)
	// Get conversation by ID
	GetConversation(context.Context, *GetConversationRequest) (*ConversationResponse, error)
	// Get user conversations
	GetUserConversations(context.Context, *GetUserConversationsRequest) (*GetUserConversationsResponse, error)
	// Add message to conversation
	AddMessage(context.Context, *AddMessageRequest) (*ConversationResponse, error)
	// Update conversation title
	UpdateConversationTitle(context.Context, *UpdateConversationTitleRequest) (*ConversationResponse, error)
	// Delete conversation
	DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error)
	mustEmbedUnimplementedConversationServiceServer()
}

// UnimplementedConversationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConversationServiceServer struct{}

func (UnimplementedConversationServiceServer) CreateConversation(context.Context, *CreateConversationRequest) (*ConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversation not implemented")
}
func (UnimplementedConversationServiceServer) GetConversation(context.Context, *GetConversationRequest) (*ConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedConversationServiceServer) GetUserConversations(context.Context, *GetUserConversationsRequest) (*GetUserConversationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserConversations not implemented")
}
func (UnimplementedConversationServiceServer) AddMessage(context.Context, *AddMessageRequest) (*ConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMessage not implemented")
}
func (UnimplementedConversationServiceServer) UpdateConversationTitle(context.Context, *UpdateConversationTitleRequest) (*ConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConversationTitle not implemented")
}
func (UnimplementedConversationServiceServer) DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedConversationServiceServer) mustEmbedUnimplementedConversationServiceServer() {}
func (UnimplementedConversationServiceServer) testEmbeddedByValue()                             {}

// UnsafeConversationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationServiceServer will
// result in compilation errors.
type UnsafeConversationServiceServer interface {
	mustEmbedUnimplementedConversationServiceServer()
}

func RegisterConversationServiceServer(s grpc.ServiceRegistrar, srv ConversationServiceServer) {
	// If the following call pancis, it indicates UnimplementedConversationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConversationService_ServiceDesc, srv)
}

func _ConversationService_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_CreateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).CreateConversation(ctx, req.(*CreateConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetUserConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetUserConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_GetUserConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetUserConversations(ctx, req.(*GetUserConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_AddMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).AddMessage(ctx, req.(*AddMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateConversationTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateConversationTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_UpdateConversationTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateConversationTitle(ctx, req.(*UpdateConversationTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).DeleteConversation(ctx, req.(*DeleteConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversationService_ServiceDesc is the grpc.ServiceDesc for ConversationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.ConversationService",
	HandlerType: (*ConversationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversation",
			Handler:    _ConversationService_CreateConversation_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _ConversationService_GetConversation_Handler,
		},
		{
			MethodName: "GetUserConversations",
			Handler:    _ConversationService_GetUserConversations_Handler,
		},
		{
			MethodName: "AddMessage",
			Handler:    _ConversationService_AddMessage_Handler,
		},
		{
			MethodName: "UpdateConversationTitle",
			Handler:    _ConversationService_UpdateConversationTitle_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _ConversationService_DeleteConversation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/agent.proto",
}

const (
	UserPreferencesService_GetUserPreferences_FullMethodName    = "/agent.UserPreferencesService/GetUserPreferences"
	UserPreferencesService_UpdateUserPreferences_FullMethodName = "/agent.UserPreferencesService/UpdateUserPreferences"
	UserPreferencesService_ResetUserPreferences_FullMethodName  = "/agent.UserPreferencesService/ResetUserPreferences"
)

// UserPreferencesServiceClient is the client API for UserPreferencesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserPreferencesServiceClient interface {
	// Get user preferences
	GetUserPreferences(ctx context.Context, in *GetUserPreferencesRequest, opts ...grpc.CallOption) (*UserPreferencesResponse, error)
	// Update user preferences
	UpdateUserPreferences(ctx context.Context, in *UpdateUserPreferencesRequest, opts ...grpc.CallOption) (*UserPreferencesResponse, error)
	// Reset user preferences
	ResetUserPreferences(ctx context.Context, in *ResetUserPreferencesRequest, opts ...grpc.CallOption) (*UserPreferencesResponse, error)
}

type userPreferencesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserPreferencesServiceClient(cc grpc.ClientConnInterface) UserPreferencesServiceClient {
	return &userPreferencesServiceClient{cc}
}

func (c *userPreferencesServiceClient) GetUserPreferences(ctx context.Context, in *GetUserPreferencesRequest, opts ...grpc.CallOption) (*UserPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPreferencesResponse)
	err := c.cc.Invoke(ctx, UserPreferencesService_GetUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userPreferencesServiceClient) UpdateUserPreferences(ctx context.Context, in *UpdateUserPreferencesRequest, opts ...grpc.CallOption) (*UserPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPreferencesResponse)
	err := c.cc.Invoke(ctx, UserPreferencesService_UpdateUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userPreferencesServiceClient) ResetUserPreferences(ctx context.Context, in *ResetUserPreferencesRequest, opts ...grpc.CallOption) (*UserPreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPreferencesResponse)
	err := c.cc.Invoke(ctx, UserPreferencesService_ResetUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserPreferencesServiceServer is the server API for UserPreferencesService service.
// All implementations must embed UnimplementedUserPreferencesServiceServer
// for forward compatibility.
type UserPreferencesServiceServer interface {
	// Get user preferences
	GetUserPreferences(context.Context, *GetUserPreferencesRequest) (*UserPreferencesResponse, error)
	// Update user preferences
	UpdateUserPreferences(context.Context, *UpdateUserPreferencesRequest) (*UserPreferencesResponse, error)
	// Reset user preferences
	ResetUserPreferences(context.Context, *ResetUserPreferencesRequest) (*UserPreferencesResponse, error)
	mustEmbedUnimplementedUserPreferencesServiceServer()
}

// UnimplementedUserPreferencesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserPreferencesServiceServer struct{}

func (UnimplementedUserPreferencesServiceServer) GetUserPreferences(context.Context, *GetUserPreferencesRequest) (*UserPreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPreferences not implemented")
}
func (UnimplementedUserPreferencesServiceServer) UpdateUserPreferences(context.Context, *UpdateUserPreferencesRequest) (*UserPreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserPreferences not implemented")
}
func (UnimplementedUserPreferencesServiceServer) ResetUserPreferences(context.Context, *ResetUserPreferencesRequest) (*UserPreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetUserPreferences not implemented")
}
func (UnimplementedUserPreferencesServiceServer) mustEmbedUnimplementedUserPreferencesServiceServer() {
}
func (UnimplementedUserPreferencesServiceServer) testEmbeddedByValue() {}

// UnsafeUserPreferencesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserPreferencesServiceServer will
// result in compilation errors.
type UnsafeUserPreferencesServiceServer interface {
	mustEmbedUnimplementedUserPreferencesServiceServer()
}

func RegisterUserPreferencesServiceServer(s grpc.ServiceRegistrar, srv UserPreferencesServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserPreferencesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserPreferencesService_ServiceDesc, srv)
}

func _UserPreferencesService_GetUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPreferencesServiceServer).GetUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPreferencesService_GetUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPreferencesServiceServer).GetUserPreferences(ctx, req.(*GetUserPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserPreferencesService_UpdateUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPreferencesServiceServer).UpdateUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPreferencesService_UpdateUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPreferencesServiceServer).UpdateUserPreferences(ctx, req.(*UpdateUserPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserPreferencesService_ResetUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUserPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserPreferencesServiceServer).ResetUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserPreferencesService_ResetUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserPreferencesServiceServer).ResetUserPreferences(ctx, req.(*ResetUserPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserPreferencesService_ServiceDesc is the grpc.ServiceDesc for UserPreferencesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserPreferencesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.UserPreferencesService",
	HandlerType: (*UserPreferencesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserPreferences",
			Handler:    _UserPreferencesService_GetUserPreferences_Handler,
		},
		{
			MethodName: "UpdateUserPreferences",
			Handler:    _UserPreferencesService_UpdateUserPreferences_Handler,
		},
		{
			MethodName: "ResetUserPreferences",
			Handler:    _UserPreferencesService_ResetUserPreferences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/agent.proto",
}
