// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/scrapper/scrapper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeRequest) Reset() {
	*x = ScrapeRequest{}
	mi := &file_proto_scrapper_scrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeRequest) ProtoMessage() {}

func (x *ScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scrapper_scrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeRequest.ProtoReflect.Descriptor instead.
func (*ScrapeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scrapper_scrapper_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScrapeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_proto_scrapper_scrapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scrapper_scrapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scrapper_scrapper_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScrapeResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ScrapeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_proto_scrapper_scrapper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scrapper_scrapper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_proto_scrapper_scrapper_proto_rawDescGZIP(), []int{2}
}

func (x *GetCompanyRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type CompanyData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Summary            string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	RawText            string                 `protobuf:"bytes,6,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	LastUpdated        string                 `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FaviconUrl         string                 `protobuf:"bytes,9,opt,name=favicon_url,json=faviconUrl,proto3" json:"favicon_url,omitempty"`
	FaviconData        string                 `protobuf:"bytes,10,opt,name=favicon_data,json=faviconData,proto3" json:"favicon_data,omitempty"`
	FaviconContentType string                 `protobuf:"bytes,11,opt,name=favicon_content_type,json=faviconContentType,proto3" json:"favicon_content_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompanyData) Reset() {
	*x = CompanyData{}
	mi := &file_proto_scrapper_scrapper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyData) ProtoMessage() {}

func (x *CompanyData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scrapper_scrapper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyData.ProtoReflect.Descriptor instead.
func (*CompanyData) Descriptor() ([]byte, []int) {
	return file_proto_scrapper_scrapper_proto_rawDescGZIP(), []int{3}
}

func (x *CompanyData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompanyData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CompanyData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompanyData) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CompanyData) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *CompanyData) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *CompanyData) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CompanyData) GetFaviconUrl() string {
	if x != nil {
		return x.FaviconUrl
	}
	return ""
}

func (x *CompanyData) GetFaviconData() string {
	if x != nil {
		return x.FaviconData
	}
	return ""
}

func (x *CompanyData) GetFaviconContentType() string {
	if x != nil {
		return x.FaviconContentType
	}
	return ""
}

var File_proto_scrapper_scrapper_proto protoreflect.FileDescriptor

const file_proto_scrapper_scrapper_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/scrapper/scrapper.proto\x12\ascraper\"@\n" +
	"\rScrapeRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"_\n" +
	"\x0eScrapeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"2\n" +
	"\x11GetCompanyRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\"\xb0\x03\n" +
	"\vCompanyData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x19\n" +
	"\braw_text\x18\x06 \x01(\tR\arawText\x12!\n" +
	"\flast_updated\x18\a \x01(\tR\vlastUpdated\x12>\n" +
	"\bmetadata\x18\b \x03(\v2\".scraper.CompanyData.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vfavicon_url\x18\t \x01(\tR\n" +
	"faviconUrl\x12!\n" +
	"\ffavicon_data\x18\n" +
	" \x01(\tR\vfaviconData\x120\n" +
	"\x14favicon_content_type\x18\v \x01(\tR\x12faviconContentType\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x84\x01\n" +
	"\aScraper\x129\n" +
	"\x06Scrape\x12\x16.scraper.ScrapeRequest\x1a\x17.scraper.ScrapeResponse\x12>\n" +
	"\n" +
	"GetCompany\x12\x1a.scraper.GetCompanyRequest\x1a\x14.scraper.CompanyDataB7Z5github.com/ByteSurgeonAmos/go-auth-stream/proto;protob\x06proto3"

var (
	file_proto_scrapper_scrapper_proto_rawDescOnce sync.Once
	file_proto_scrapper_scrapper_proto_rawDescData []byte
)

func file_proto_scrapper_scrapper_proto_rawDescGZIP() []byte {
	file_proto_scrapper_scrapper_proto_rawDescOnce.Do(func() {
		file_proto_scrapper_scrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scrapper_scrapper_proto_rawDesc), len(file_proto_scrapper_scrapper_proto_rawDesc)))
	})
	return file_proto_scrapper_scrapper_proto_rawDescData
}

var file_proto_scrapper_scrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_scrapper_scrapper_proto_goTypes = []any{
	(*ScrapeRequest)(nil),     // 0: scraper.ScrapeRequest
	(*ScrapeResponse)(nil),    // 1: scraper.ScrapeResponse
	(*GetCompanyRequest)(nil), // 2: scraper.GetCompanyRequest
	(*CompanyData)(nil),       // 3: scraper.CompanyData
	nil,                       // 4: scraper.CompanyData.MetadataEntry
}
var file_proto_scrapper_scrapper_proto_depIdxs = []int32{
	4, // 0: scraper.CompanyData.metadata:type_name -> scraper.CompanyData.MetadataEntry
	0, // 1: scraper.Scraper.Scrape:input_type -> scraper.ScrapeRequest
	2, // 2: scraper.Scraper.GetCompany:input_type -> scraper.GetCompanyRequest
	1, // 3: scraper.Scraper.Scrape:output_type -> scraper.ScrapeResponse
	3, // 4: scraper.Scraper.GetCompany:output_type -> scraper.CompanyData
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_scrapper_scrapper_proto_init() }
func file_proto_scrapper_scrapper_proto_init() {
	if File_proto_scrapper_scrapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scrapper_scrapper_proto_rawDesc), len(file_proto_scrapper_scrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scrapper_scrapper_proto_goTypes,
		DependencyIndexes: file_proto_scrapper_scrapper_proto_depIdxs,
		MessageInfos:      file_proto_scrapper_scrapper_proto_msgTypes,
	}.Build()
	File_proto_scrapper_scrapper_proto = out.File
	file_proto_scrapper_scrapper_proto_goTypes = nil
	file_proto_scrapper_scrapper_proto_depIdxs = nil
}
